# Generated by Django 5.2.14 on 2026-06-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0119_alter_stockitemtestresult_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Use {location_id} placeholder for the location PK",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("hours_updated", "Hours Updated")],
                        max_length=50,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("manual", "Manual Only"), ("on_save", "On Save")],
                        default="manual",
                        max_length=20,
                        verbose_name="Trigger",
                    ),
                ),
                (
                    "secret_env_var",
                    models.CharField(
                        blank=True,
                        help_text="Name of environment variable holding the API key (never stored in DB)",
                        max_length=100,
                        verbose_name="Secret Env Variable",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional endpoint-specific overrides",
                        verbose_name="Config",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Event Type"),
                ),
                (
                    "request_url",
                    models.URLField(max_length=1000, verbose_name="Request URL"),
                ),
                (
                    "request_body",
                    models.TextField(blank=True, verbose_name="Request Body"),
                ),
                (
                    "response_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Response Code"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="Response Body"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="stock.stocklocation",
                        verbose_name="Location",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="inventree_location_hours.webhookendpoint",
                        verbose_name="Webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LocationHours",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True,
                        help_text="Leave blank if closed on this day",
                        null=True,
                        verbose_name="Open Time",
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(blank=True, null=True, verbose_name="Close Time"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_hours",
                        to="stock.stocklocation",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Hours",
                "verbose_name_plural": "Location Hours",
                "ordering": ["location", "day"],
                "unique_together": {("location", "day")},
            },
        ),
    ]
