# Generated by Django 5.2.14 on 2026-06-06 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventree_location_hours", "0004_googleoauthtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookendpoint",
            name="api_key_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Stored API key used to authenticate outgoing webhooks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_endpoints",
                to="inventree_location_hours.locationapikey",
                verbose_name="API Key",
            ),
        ),
    ]
