# Generated by Django 5.2.14 on 2026-06-03 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0079_auto_20260212_1054"),
        ("stock", "0119_alter_stockitemtestresult_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="POSTerminal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terminal_id",
                    models.SlugField(
                        help_text="Unique identifier sent in the webhook payload",
                        max_length=100,
                        unique=True,
                        verbose_name="Terminal ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this terminal",
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "receipt_api_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="External POS API URL that returns receipt line items",
                        max_length=500,
                        verbose_name="Receipt API Endpoint",
                    ),
                ),
                (
                    "receipt_api_key",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted at rest. Set via the management UI.",
                        verbose_name="Receipt API Key",
                    ),
                ),
                (
                    "service_username",
                    models.CharField(
                        default="admin",
                        help_text="InvenTree user account used to create orders",
                        max_length=150,
                        verbose_name="Service User",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer company for sales orders",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_terminals",
                        to="company.company",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where stock is pulled from for sales from this terminal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_terminals",
                        to="stock.stocklocation",
                        verbose_name="Stock Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS Terminal",
                "verbose_name_plural": "POS Terminals",
                "ordering": ["name"],
            },
        ),
    ]
